### ISSUE TITLE
Acquiring Techs Causing Error

### ISSUE THREAD

**Issue by TaylorBoyd** [AsyncEclipse/DiscordBot#63]
2024-09-20 00:06:44 ERROR    discord.client Ignoring exception in on_interaction
Traceback (most recent call last):
  File "/home/eatingflowers/.local/lib/python3.10/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/home/eatingflowers/DiscordBot/./listeners/ButtonListener.py", line 70, in on_interaction
    await ResearchButtons.getTech(game, player, player_helper, interaction)
  File "/home/eatingflowers/DiscordBot/./Buttons/Research.py", line 158, in getTech
    await ResearchButtons.handle_specific_tech_selection(interaction, game, player, tech_details, tech_type,tech)
  File "/home/eatingflowers/DiscordBot/./Buttons/Research.py", line 24, in handle_specific_tech_selection
    cost = ResearchButtons.calculate_cost(tech_details, tech_type,player)
  File "/home/eatingflowers/DiscordBot/./Buttons/Research.py", line 72, in calculate_cost
    len(player[f"{tech_type}_tech"]) if tech_type != "any"
KeyError: 'nar_tech'

**Comment by Fingon00** [comment]
Ah, it's broke cause it's not parsing the buttonID properly. Easy fix. Done
