### ISSUE TITLE
Incorrect Tech Name. "clo" needs to be changed to the correct version

### ISSUE THREAD

**Issue by TaylorBoyd** [AsyncEclipse/DiscordBot#64]
Traceback (most recent call last):
  File "/home/eatingflowers/.local/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/home/eatingflowers/.local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "/home/eatingflowers/.local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'game' raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction
2024-09-19 18:55:25 ERROR    discord.app_commands.tree Ignoring exception in command 'game'
Traceback (most recent call last):
  File "/home/eatingflowers/.local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 857, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "/home/eatingflowers/DiscordBot/./commands/setup_commands.py", line 88, in game
    game.setup_finished()
  File "/home/eatingflowers/DiscordBot/./helpers/GamestateHelper.py", line 324, in setup_finished
    if tech_data[picked_tech]["track"] == "any":
KeyError: 'clo'

**Comment by Fingon00** [comment]
Changed to "cld"
