### ISSUE TITLE
Rare Ship Part Cannot Be Added - HyperGrid Source

### ISSUE THREAD

**Issue by TaylorBoyd** [AsyncEclipse/DiscordBot#76]
Looks like a mistyped key:

2024-09-20 23:45:06 ERROR    discord.client Ignoring exception in on_interaction
Traceback (most recent call last):
  File "/home/eatingflowers/.local/lib/python3.10/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/home/eatingflowers/DiscordBot/./listeners/ButtonListener.py", line 94, in on_interaction
    await UpgradeButtons.selectOldPart(game, player, interaction, customID,player_helper)
  File "/home/eatingflowers/DiscordBot/./Buttons/Upgrade.py", line 57, in selectOldPart
    await UpgradeButtons.chooseUpgrade(game, player, interaction, customID+"_"+discTileUpgrade,player_helper)
  File "/home/eatingflowers/DiscordBot/./Buttons/Upgrade.py", line 100, in chooseUpgrade
    shipCheck = PlayerShip(player_helper.stats, ship)
  File "/home/eatingflowers/DiscordBot/./helpers/ShipHelper.py", line 59, in __init__
    self.build_ship_stats(self.ship_parts)
  File "/home/eatingflowers/DiscordBot/./helpers/ShipHelper.py", line 24, in build_ship_stats
    part_stats = part_dict[part]
KeyError: 'hys'

**Comment by Fingon00** [comment]
Changed to hyg, since that matches the part
