### ISSUE TITLE
Unknown Issue Popping Up

### ISSUE THREAD

**Issue by TaylorBoyd** [AsyncEclipse/DiscordBot#77]
Showing up multiple times in the logs:

2024-09-20 23:46:29 ERROR    discord.client Ignoring exception in on_interaction
Traceback (most recent call last):
  File "/home/eatingflowers/.local/lib/python3.10/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/home/eatingflowers/DiscordBot/./listeners/ButtonListener.py", line 46, in on_interaction
    await TurnButtons.permanentlyPass(player, game, interaction,player_helper)
  File "/home/eatingflowers/DiscordBot/./Buttons/Turn.py", line 87, in permanentlyPass
    await interaction.response.edit_message(content="You permanently passed", view=None)
  File "/home/eatingflowers/.local/lib/python3.10/site-packages/discord/interactions.py", line 990, in edit_message
    await adapter.create_interaction_response(
  File "/home/eatingflowers/.local/lib/python3.10/site-packages/discord/webhook/async_.py", line 221, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

**Comment by Fingon00** [comment]
Fixed
